/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.matuyuhi.apiclient.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.matuyuhi.apiclient.apis.UsersApi
import com.matuyuhi.apiclient.models.ListUsers200ResponseInner
import com.matuyuhi.apiclient.models.ShowUserById404Response

class UsersApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UsersApi
        //val apiInstance = UsersApi()

        // to test createUser
        should("test createUser") {
            // uncomment below to test createUser
            //val listUsers200ResponseInner : ListUsers200ResponseInner =  // ListUsers200ResponseInner | 
            //val result : ListUsers200ResponseInner = apiInstance.createUser(listUsers200ResponseInner)
            //result shouldBe ("TODO")
        }

        // to test listUsers
        should("test listUsers") {
            // uncomment below to test listUsers
            //val result : kotlin.collections.List<ListUsers200ResponseInner> = apiInstance.listUsers()
            //result shouldBe ("TODO")
        }

        // to test showUserById
        should("test showUserById") {
            // uncomment below to test showUserById
            //val userId : kotlin.String = userId_example // kotlin.String | The id of the user to retrieve
            //val result : ListUsers200ResponseInner = apiInstance.showUserById(userId)
            //result shouldBe ("TODO")
        }

    }
}
