/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.matuyuhi.apiclient.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 
 *
 * @param id 
 * @param name 
 * @param tag 
 */
@Parcelize


data class ListUsers200ResponseInner (

    @Json(name = "id")
    val id: kotlin.Long,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "tag")
    val tag: kotlin.String? = null

) : Parcelable {


}

