/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.matuyuhi.apiclient.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 
 *
 * @param code 
 * @param message 
 */
@Parcelize


data class ShowUserById404Response (

    @Json(name = "code")
    val code: kotlin.Int,

    @Json(name = "message")
    val message: kotlin.String

) : Parcelable {


}

