/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.matuyuhi.apiclient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.matuyuhi.apiclient.models.ShowUserById404Response

class ShowUserById404ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ShowUserById404Response
        //val modelInstance = ShowUserById404Response()

        // to test the property `code`
        should("test code") {
            // uncomment below to test the property
            //modelInstance.code shouldBe ("TODO")
        }

        // to test the property `message`
        should("test message") {
            // uncomment below to test the property
            //modelInstance.message shouldBe ("TODO")
        }

    }
}
